# Generated by Django 2.1.7 on 2019-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='status',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
