# Generated by Django 2.1.7 on 2019-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20190411_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='status',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
