# Generated by Django 2.1.7 on 2019-03-29 08:33

from django.db import migrations, models

# makemigrations 하면 생기는 파일.
# db에 공간 만드려면 python manage.py migrate
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=37.564214)),
                ('long', models.FloatField(default=127.001699)),
                ('memo', models.TextField()),
                ('status', models.ImageField(upload_to='')),
            ],
        ),
    ]
